### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by CBhavsar-Fintech** [roozbehid/GCCTask#15]
Hi Roozbehind- I followed all steps mentioned on the page. but when I try to build it from visual studio. I get the below error. please suggest.

![image](https://user-images.githubusercontent.com/41365532/94123324-46c07900-fe71-11ea-964b-b29c6bb3cd04.png)

**Comment by roozbehid** [comment]
Do you have .net core installed on your system?
what happens when you do instructions based on cli commands ie, dotnet build?

**Comment by CBhavsar-Fintech** [comment]
I tried cli dotnet build command. but getting error msg like below.

![image](https://user-images.githubusercontent.com/41365532/94253517-0e896b00-ff43-11ea-94f2-24a261242ced.png)

**Comment by roozbehid** [comment]
![image](https://user-images.githubusercontent.com/7875383/94394056-a640b200-0119-11eb-9d13-05df00f402b0.png)

You need to have LinuxDebug or LinuxRelease then also specify them in your arguments to dontet buid.
Probably like

    dotnet build /p:Configuration=LinuxDebug

**Comment by roozbehid** [comment]
You can clone this repo and see if you can build examples or not

**Comment by CBhavsar-Fintech** [comment]
OK. I have tried build example. please see error as below
![image](https://user-images.githubusercontent.com/41365532/94648632-917a3f00-0310-11eb-80e7-1e80279aeac1.png)

**Comment by roozbehid-ic** [comment]
Have you created LinuxDebug and LinuxRelease configurations for the projects?

**Comment by roozbehid** [comment]
![image](https://user-images.githubusercontent.com/7875383/94709050-86b8ad80-0302-11eb-828e-9203a187d1d5.png)

So here are steps I did to make it work on Windows.

- add path to GCC
- dotnet build /p:Configuration=LinuxDebug
- I built VcxProj_Complex which contains dynamic library, static library and c# code in one solution

**Comment by CBhavsar-Fintech** [comment]
Yes, It works with the example.

**Comment by CBhavsar-Fintech** [comment]
Yes, It works with the example.
