### ISSUE TITLE
Is it intentional that everything what Linker writes into stderr is treated as error

### ISSUE THREAD

**Issue by piomis** [roozbehid/GCCTask#24]
One of my compier/linker wrappers writes some "banner" info to stderr (but exit code is 0 - so process is successful).
I have noticed that  this info is logged during building and displayed again after whole build.

What is more interesting that Compile step uses XBuildLogProvieder.LogOther method which things which do not fit into none of regexp  treats as Warnings.
But Linker step calls XBuildLogProvider.LogLinker whch things which do not match any regexp logs es errors.
Is it intentional?

**Comment by roozbehid** [comment]
Yeah. So mostly I wrote this for my webassembly project so I can build my stuff for webassembly and I think everything that emscripten linker was puting out shouldve been treated as errors.
But honestly I dont recall it anymore.

But overall my problem with all these categorization of logs was they were not consistent among different compilers. So eventually what you see is what made my compilers and me happy for my few projects.
I really appreciate a PR if you think behavior can be enhanced.

And Also I will pish new version ASAP

**Comment by piomis** [comment]
I will try to think about it - maybe configurable regexp would do the job.

In regards to push - maybe you would like to check hanging PR before making new release on nuget.org :)

**Comment by roozbehid** [comment]
I pushed 1.22.77.8

**Comment by roozbehid** [comment]
Thanks to you first update after 3 years :D
