### ISSUE TITLE
Install instruction please

### ISSUE THREAD

**Issue by edperry** [roozbehid/GCCTask#28]
I saw a ticket that was closed, and I agree the main readme does not explain, if this repo needs to be checked out in to its own repo, part of my existing code base nor any setup needed other then the 2 commands. 

https://github.com/roozbehid/dotnet-vcxproj/issues/3

It would be greatly appreciated if you added steps for people not familiar with this process. I found this repo based on error messages and just trying to get my code to compile with Linux GCC. I know nothing about DOTNET

**Comment by roozbehid** [comment]
You need dotnet sdk installed to use this. Although it builds c++ code but it used msbuild to orchestrade calls to gcc and uses dotnet to distribute thr package for you to use.
So you need .net sdk installed
