### ISSUE TITLE
The readme dives right into using GCCBuild without giving any information on  how to build and install it.

### ISSUE THREAD

**Issue by BenKey** [roozbehid/GCCTask#3]
The readme dives right into using GCCBuild without giving any information on  how to build and install it. This makes it unnecessarily difficult for someone who is unfamiliar with these steps to use the project.

Please provide these missing details.

**Comment by roozbehid** [comment]
Well I had a feeling that it was clear....but if you think there are missing steps. I will try to elaborate more.
The thing is as this project is deployed to nuget.org, theoretically, there is no need to build or do anything with this source. You can just go ahead and use it. Thats why maybe it felt confusing. No need for installation or building or anything. 

But if you want to make modifications or contributions then you have to clone, build and install it

**Comment by BenKey** [comment]
So how do you install it?

**Comment by roozbehid** [comment]
As it was outlined in the readme
`dotnet new -i GCC.Build.Template`
Will install the template for dotnet. (Assumption is you already installed dotnet SDK for your system)
then
`dotnet new gccbuild` will transform your current .vcxproj into using GCCBuild.

**Comment by BenKey** [comment]
After reading the documentation for the dotnet new command, I now understand. Thanks.
