### ISSUE TITLE
Problems with relative pathes

### ISSUE THREAD

**Issue by ebertw** [roozbehid/GCCTask#5]
If "IntDir" or "OutDir" starts with a dot or a dotdot (relative path) the CCompilerTask crashes, because the constructor of "Uri" (File: Utilities.cs, function MakeRelative) does not work with such URIs. This happens after compilation and before linking, while msbuild is collecting the object files for the linker.

A possible solution could be to check for "." and ".." right before the assignment

var fileUri = new Uri(filePath);

like this:

string tempPath = filePath;

if (tempPath.startsWith('.'))
    tempPath = referencePath + filePath;

var fileUri = new Uri(tempPath);

...

**Comment by roozbehid** [comment]
should be fixed in most recent version

**Comment by ebertw** [comment]
Sorry, but the fix does not work for relative pathes wich does not start with a dot. I did not seen it before, but now it happens on a project. I fixed it in my copy as I'm replacing the if-statement with

if (Path.IsPathRooted(filePath) == false)

Maybe this could be the final solution.

**Comment by roozbehid** [comment]
Can you provide more code, example or info?
Because in my test I actually used a path that starts with dot in OutDir and it worked.

**Comment by ebertw** [comment]
Hi,

 

yes, that should be no problem, but I need some time. But: how should I provide the code?

 

Kind regards

Wolfgang

 

Von: roozbehid <notifications@github.com> 
Gesendet: Mittwoch, 27. März 2019 18:48
An: roozbehid/dotnet-vcxproj <dotnet-vcxproj@noreply.github.com>
Cc: Wolfgang Ebert <wolfgang.ebert@argoedv.de>; Author <author@noreply.github.com>
Betreff: Re: [roozbehid/dotnet-vcxproj] Problems with relative pathes (#5)

 

Can you provide more code, example or info?
Because in my test I actually used a path that starts with dot in OutDir and it worked.

**Comment by ebertw** [comment]
I checked it again, and I have to apologize: you’re right. Your code works. I mixed it with another error which was made by me. I’m sorry for this.

 

Kind regards

Wolfgang

Von: roozbehid <notifications@github.com> 
Gesendet: Mittwoch, 27. März 2019 18:48
An: roozbehid/dotnet-vcxproj <dotnet-vcxproj@noreply.github.com>
Cc: Wolfgang Ebert <wolfgang.ebert@argoedv.de>; Author <author@noreply.github.com>
Betreff: Re: [roozbehid/dotnet-vcxproj] Problems with relative pathes (#5)

 

Can you provide more code, example or info?
Because in my test I actually used a path that starts with dot in OutDir and it worked.
