### ISSUE TITLE
Includeflag for gcc

### ISSUE THREAD

**Issue by ebertw** [roozbehid/GCCTask#6]
The original line in Microsoft.Cpp.props is <Flag>-I &quot;@{;}&quot;</Flag>. But this line cause some problems while using the gcc as a cross-compiler under Windows. The generated command line is gcc ... -I "<directory-name>\" with a backslash right before the second quote. Unfortunately gcc think, that you want to escape the quote and ignore it. And this could end in a "gcc: no input files" error.

I understand, why you quoted the include path, but I fear, that this is not really correct.

**Comment by roozbehid** [comment]
Should be fixed in most recent version
