### ISSUE TITLE
C++ project built with gcc but not g++

### ISSUE THREAD

**Issue by jonathan-ruiz** [roozbehid/GCCTask#8]
Ubuntu 18.04
netcore 2.2

Project builds correctly when std is not used but as soon as iostream is added I got errors like:
 undefined reference to `std::cout'

Code: 
```
#include <iostream>

int main()
{
	std::cout << "Hello World!" << std::endl;
	return 0;
}

```

replacing std::cout with printf everything works fine, so looks like it is using gcc to compile and not g++

**Comment by roozbehid** [comment]
What is the extension of the file? I think my assumption was use gcc if it is .c use g++ if it .cpp

**Comment by jonathan-ruiz** [comment]
Hi,
the extension is .cpp

a screenshot with a "ls" of the building directory:

![image](https://user-images.githubusercontent.com/26813946/57680409-d58e7600-762d-11e9-945a-ae234a7f8630.png)

To clarify, the error I'm getting is exactly the same as when I try to compile the c++ file with gcc instead of g++.
This is why I'm assuming mbsbuild is using gcc instead of g++.

But that could be a mistaken assumption.

Where in your code is the extension checked to do the switch between one compiler or another?

I just found this mention to the compiler in the code:
GCCBuild/Compilers/CCompilerTask.cs:        private const string DefaultCompiler = "gcc.exe";

But not even sure if this is the version of your template that msbuild is actually using 


Thanks

**Comment by jonathan-ruiz** [comment]
a screenshot with an ls of the building directory:

![image](https://user-images.githubusercontent.com/26813946/57680409-d58e7600-762d-11e9-945a-ae234a7f8630.png)

**Comment by jonathan-ruiz** [comment]
To clarify, the error I'm getting is exactly the same as when I try to compile the c++ file with gcc instead of g++. 
This is why I'm assuming mbsbuild is using gcc instead of g++.

But that could be a mistaken assumption. 

Where in your code is the extension checked to do the switch between one compiler or another?

Thanks

**Comment by roozbehid** [comment]
please test again...should be fixed with recent version
