### ISSUE TITLE
IncludeDirs?

### ISSUE THREAD

**Issue by reardenlife** [roozbehid/GCCTask#9]
I am trying to build a Microsoft Visual Studio project with c++ code on CentOS7.  I installed dotnet 2.2 and this project nicely solved a issue with non-existent build rules for c++ compiler.  However I still need to specify a path to Windows SDK to successfully build an app.  I found w32api-5.2.2-mingw32 which has windows.h & co.  How I can specify a path to it in the configuration files of ... project?  dotnet itself?

**Comment by roozbehid** [comment]
It should be the same as editing vcxproj file. You just need to put include dir in your compiler include settings.
But you do realize it probably wont work, right?You should somehow get rid of using Windows SDK if you want to build in linux...
